Design change related to issue #100
ArnesSI/netbox-inventory pull request #101
Opened 2023-05-06 15:20 UTC by nicholsk18

I had to change the way data is being passed to the template for a cleaner and easier way to loop over that data.
Let me know if something needs to be refactored in `inventoryitem_group.py` file. Python is not my go-to language 😄

2023-05-24 17:30 UTC, matejv requested changes
Thank you for your contribution. I made a couple of suggestions to use status label in template.

Other than that the code seems fine and the end result looks great!

2023-05-24 17:30 UTC, matejv commented on netbox_inventory/views/inventoryitem_group.py
> +                'color': tsc['color']
```suggestion
                'color': tsc['color'],
                'label': tsc['label']
```

Add status label (aka display)

2023-05-24 17:30 UTC, matejv commented on netbox_inventory/templates/netbox_inventory/inventoryitemgroup.html
> +                    {% badge value=status.status|capfirst|add:' - '|add:status.count bg_color=status.color|add:' w-100' %}
```suggestion
                    {% badge value=status.label|add:' - '|add:status.count bg_color=status.color|add:' w-100' %}
```

I suggest using status label here. 

At least we use localized custom status values, so displaying them consistently throughout UI is desirable.

2023-05-25 11:14 UTC, nicholsk18 commented
Thank you for the review, label does make more sense there. I also added overflow, for people who might have many badges, so it doesn't break their UI.

2023-05-25 11:45 UTC, merged